export const DOCUMENT_UPLOAD_MAX_SIZE_GB = 50;
export const DOCUMENT_UPLOAD_MAX_SIZE_BYTES =
  DOCUMENT_UPLOAD_MAX_SIZE_GB * 1024 * 1024 * 1024;
export const DOCUMENT_UPLOAD_MAX_SIZE_LABEL = `${DOCUMENT_UPLOAD_MAX_SIZE_GB}GB`;
export const DOCUMENT_UPLOAD_EMPTY_META = `PDF, DOC, XLS, atau gambar. Maksimal ${DOCUMENT_UPLOAD_MAX_SIZE_LABEL}.`;
