export const DOCUMENT_UPLOAD_MAX_SIZE_MB = 50;
export const DOCUMENT_UPLOAD_MAX_SIZE_BYTES =
  DOCUMENT_UPLOAD_MAX_SIZE_MB * 1024 * 1024;
export const DOCUMENT_UPLOAD_MAX_SIZE_LABEL = `${DOCUMENT_UPLOAD_MAX_SIZE_MB} MB`;
export const DOCUMENT_UPLOAD_EMPTY_META = `PDF, DOC, PPT, XLS, atau gambar. Maksimal ${DOCUMENT_UPLOAD_MAX_SIZE_LABEL}.`;
