export type ModalKind =
  | "audit"
  | "confirmation"
  | "detail"
  | "form"
  | "picker"
  | "summary"
  | "workflow";

export type ModalDataCondition = "empty" | "long-text" | "normal";

export type ModalViewportStatus =
  | "needs-fix"
  | "not-verified"
  | "passed";

export type ModalAuditEvidence = "runtime-e2e" | "source-only";

export type ModalRuntimeEvidence = Partial<
  Record<"desktop" | "tablet" | "mobile", readonly string[]>
>;

export type ModalCallerBaseline = {
  id: string;
  source: string;
  ordinal: number;
  owner: string;
  routes: readonly string[];
  title: string;
  trigger: {
    label: string;
    source?: string;
    tokens: readonly string[];
  };
  kind: ModalKind;
  dataConditions: readonly ModalDataCondition[];
  viewport: {
    desktop: ModalViewportStatus;
    tablet: ModalViewportStatus;
    mobile: ModalViewportStatus;
  };
  evidence: ModalAuditEvidence;
  runtimeEvidence: ModalRuntimeEvidence;
};

type ModalCallerSourceInventoryEntry = Omit<
  ModalCallerBaseline,
  "evidence" | "runtimeEvidence"
> & {
  evidence: "source-only" | "visual";
};

const PASS_ALL = {
  desktop: "passed",
  tablet: "passed",
  mobile: "passed",
} as const;

const NEEDS_FIX_ALL = {
  desktop: "needs-fix",
  tablet: "needs-fix",
  mobile: "needs-fix",
} as const;

const MOBILE_NEEDS_FIX = {
  desktop: "passed",
  tablet: "passed",
  mobile: "needs-fix",
} as const;

const DETAIL_DATA = ["normal", "long-text"] as const;
const FORM_DATA = ["empty", "normal", "long-text"] as const;
const SUMMARY_DATA = ["empty", "normal", "long-text"] as const;

const dashboardRoute = ["/dashboard"] as const;
const debtorDetailRoute = ["/dashboard/informasi-debitur/[id]"] as const;
const debtorImportRoutes = [
  "/dashboard/informasi-debitur/admin/monitoring-import",
  "/dashboard/informasi-debitur/admin/upload-ideb",
  "/dashboard/informasi-debitur/admin/upload-slik",
] as const;
const debtorMarketingRoutes = [
  "/dashboard/informasi-debitur/marketing/action-plan",
  "/dashboard/informasi-debitur/marketing/hasil-kunjungan",
  "/dashboard/informasi-debitur/marketing/langkah-penanganan",
] as const;
const legalProgressRoutes = [
  "/dashboard/legal/progress/asuransi",
  "/dashboard/legal/progress/kjpp",
  "/dashboard/legal/progress/notaris",
] as const;
const legalDepositRoutes = [
  "/dashboard/legal/titipan/angsuran",
  "/dashboard/legal/titipan/asuransi",
  "/dashboard/legal/titipan/lainnya",
  "/dashboard/legal/titipan/notaris",
] as const;
const parameterMasterRoutes = [
  "/dashboard/parameter/cabang",
  "/dashboard/parameter/checklist-dokumen",
  "/dashboard/parameter/jenis-agunan",
  "/dashboard/parameter/jenis-akad",
  "/dashboard/parameter/jenis-proses-legal",
  "/dashboard/parameter/jenis-titipan",
  "/dashboard/parameter/media-pengiriman-surat",
  "/dashboard/parameter/pihak-ketiga/kjpp",
  "/dashboard/parameter/pihak-ketiga/notaris",
  "/dashboard/parameter/pihak-ketiga/perusahaan-asuransi",
  "/dashboard/parameter/produk-pembiayaan",
] as const;
const storageOverviewRoute = [
  "/dashboard/arsip-digital/ruang-arsip/tempat-penyimpanan",
] as const;
const storageLegacyRoute = [
  "/dashboard/arsip-digital/ruang-arsip/tempat-penyimpanan/[kantorId]",
] as const;

const MODAL_CALLER_SOURCE_INVENTORY: readonly ModalCallerSourceInventoryEntry[] = [
  {
    id: "disposisi-historis-detail",
    source: "src/app/dashboard/arsip-digital/disposisi/historis/page.tsx",
    ordinal: 1,
    owner: "HistorisDisposisiPage",
    routes: ["/dashboard/arsip-digital/disposisi/historis"],
    title: "Detail Disposisi",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "disposisi-permintaan-action",
    source: "src/app/dashboard/arsip-digital/disposisi/permintaan/page.tsx",
    ordinal: 1,
    owner: "PermintaanDisposisiPage",
    routes: ["/dashboard/arsip-digital/disposisi/permintaan"],
    title: "Detail / Setujui / Tolak Permintaan Disposisi",
    trigger: {
      label: "Detail, Setujui, atau Tolak",
      tokens: ['label: "Detail"', 'label: "Setujui"', 'label: "Tolak"'],
    },
    kind: "workflow",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "peminjaman-historis-detail",
    source: "src/app/dashboard/arsip-digital/historis/peminjaman/page.tsx",
    ordinal: 1,
    owner: "HistorisPeminjamanPage",
    routes: ["/dashboard/arsip-digital/historis/peminjaman"],
    title: "Detail Historis Peminjaman",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "penyimpanan-historis-detail",
    source: "src/app/dashboard/arsip-digital/historis/penyimpanan/page.tsx",
    ordinal: 1,
    owner: "HistorisPenyimpananPage",
    routes: ["/dashboard/arsip-digital/historis/penyimpanan"],
    title: "Detail Historis Penyimpanan",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "peminjaman-approval-action",
    source: "src/app/dashboard/arsip-digital/peminjaman/accept/page.tsx",
    ordinal: 1,
    owner: "AcceptPeminjamanPage",
    routes: ["/dashboard/arsip-digital/peminjaman/accept"],
    title: "Setujui / Tolak / Serah Terima / Pengembalian Peminjaman",
    trigger: {
      label: "Setujui, Tolak, Serahkan Dokumen, atau Catat Pengembalian",
      tokens: [
        'label: "Setujui"',
        'label: "Tolak"',
        'label: "Serahkan Dokumen"',
        'label: "Catat Pengembalian"',
      ],
    },
    kind: "workflow",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "peminjaman-approval-detail",
    source: "src/app/dashboard/arsip-digital/peminjaman/accept/page.tsx",
    ordinal: 2,
    owner: "AcceptPeminjamanPage",
    routes: ["/dashboard/arsip-digital/peminjaman/accept"],
    title: "Detail Peminjaman",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "peminjaman-laporan-detail",
    source: "src/app/dashboard/arsip-digital/peminjaman/laporan/page.tsx",
    ordinal: 1,
    owner: "LaporanPeminjamanPage",
    routes: ["/dashboard/arsip-digital/peminjaman/laporan"],
    title: "Detail Peminjaman",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "peminjaman-request-form",
    source: "src/app/dashboard/arsip-digital/peminjaman/request/page.tsx",
    ordinal: 1,
    owner: "RequestPeminjamanPage",
    routes: ["/dashboard/arsip-digital/peminjaman/request"],
    title: "Ajukan Peminjaman",
    trigger: { label: "Ajukan Pinjam", tokens: ["Ajukan Pinjam", "setShowModal(true)"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "dokumen-list-detail",
    source: "src/app/dashboard/arsip-digital/ruang-arsip/list-dokumen/page.tsx",
    ordinal: 1,
    owner: "ListDokumenPage",
    routes: ["/dashboard/arsip-digital/ruang-arsip/list-dokumen"],
    title: "Detail Dokumen",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setShowDetail(true)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "dokumen-list-edit",
    source: "src/app/dashboard/arsip-digital/ruang-arsip/list-dokumen/page.tsx",
    ordinal: 2,
    owner: "ListDokumenPage",
    routes: ["/dashboard/arsip-digital/ruang-arsip/list-dokumen"],
    title: "Edit Dokumen",
    trigger: { label: "Edit", tokens: ['label: "Edit"', "setShowEdit(true)"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-divisi-form",
    source: "src/app/dashboard/parameter/divisi/page.tsx",
    ordinal: 1,
    owner: "SetupDivisiPage",
    routes: ["/dashboard/parameter/divisi"],
    title: "Tambah / Edit Divisi",
    trigger: { label: "Tambah Divisi atau Edit", tokens: ["Tambah Divisi", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-jenis-dokumen-form",
    source: "src/app/dashboard/parameter/jenis-dokumen/page.tsx",
    ordinal: 1,
    owner: "SetupJenisDokumenPageContent",
    routes: ["/dashboard/parameter/jenis-dokumen"],
    title: "Tambah / Edit Jenis Dokumen",
    trigger: { label: "Tambah Jenis atau Edit", tokens: ["Tambah Jenis", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-prioritas-surat-form",
    source: "src/app/dashboard/parameter/prioritas-surat/page.tsx",
    ordinal: 1,
    owner: "SetupPrioritasSuratPage",
    routes: ["/dashboard/parameter/prioritas-surat"],
    title: "Tambah / Edit Prioritas Surat",
    trigger: { label: "Tambah Prioritas atau Edit", tokens: ["Tambah Prioritas", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-role-form",
    source: "src/app/dashboard/parameter/role/page.tsx",
    ordinal: 1,
    owner: "SetupRolePage",
    routes: ["/dashboard/parameter/role"],
    title: "Tambah / Edit Role",
    trigger: { label: "Tambah Role atau Edit", tokens: ["Tambah Role", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-role-menu-feature",
    source: "src/app/dashboard/parameter/role-menu/page.tsx",
    ordinal: 1,
    owner: "SetupRoleMenuPage",
    routes: ["/dashboard/parameter/role-menu"],
    title: "Atur Fitur Role",
    trigger: { label: "Atur fitur", tokens: ["Atur fitur", "setFeatureModalMenuId(row.menu.id)"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-tempat-penyimpanan-form",
    source: "src/app/dashboard/parameter/tempat-penyimpanan/page.tsx",
    ordinal: 1,
    owner: "SetupTempatPenyimpananPageContent",
    routes: ["/dashboard/parameter/tempat-penyimpanan"],
    title: "Tambah / Edit Tempat Penyimpanan",
    trigger: { label: "Tambah Tempat atau Edit", tokens: ["Tambah Tempat", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "users-form",
    source: "src/app/dashboard/users/page.tsx",
    ordinal: 1,
    owner: "ManajemenUserPage",
    routes: ["/dashboard/users"],
    title: "Tambah / Edit Pengguna",
    trigger: { label: "Tambah Pengguna atau Edit", tokens: ["Simpan & Kirim Undangan", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "users-invitation-ready",
    source: "src/app/dashboard/users/page.tsx",
    ordinal: 2,
    owner: "ManajemenUserPage",
    routes: ["/dashboard/users"],
    title: "Undangan Siap Dibagikan",
    trigger: { label: "Simpan & Kirim Undangan", tokens: ["Simpan & Kirim Undangan", "setManualInvitation"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "users-access-action",
    source: "src/app/dashboard/users/page.tsx",
    ordinal: 3,
    owner: "ManajemenUserPage",
    routes: ["/dashboard/users"],
    title: "Tutup / Aktifkan Kembali Akses Pengguna",
    trigger: { label: "Tutup Akses atau Aktifkan Kembali", tokens: ['label: user.is_active ? "Tutup Akses" : "Aktifkan Kembali"'] },
    kind: "confirmation",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "users-delete-confirmation",
    source: "src/app/dashboard/users/page.tsx",
    ordinal: 4,
    owner: "ManajemenUserPage",
    routes: ["/dashboard/users"],
    title: "Hapus Pengguna Permanen",
    trigger: { label: "Hapus", tokens: ['label: "Hapus"', "setShowDelete(true)"] },
    kind: "confirmation",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "activity-centre-detail",
    source: "src/components/activity-centre/ActivityCentreClient.tsx",
    ordinal: 1,
    owner: "ActivityDetailModal",
    routes: ["/dashboard/activity-centre"],
    title: "Detail Aktivitas",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "openDetail(item)"] },
    kind: "audit",
    dataConditions: DETAIL_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "visual",
  },
  {
    id: "storage-document-list",
    source: "src/components/arsip/DokumenListModal.tsx",
    ordinal: 1,
    owner: "DokumenListModal",
    routes: storageOverviewRoute,
    title: "Daftar Dokumen Rak",
    trigger: {
      label: "Lihat Dokumen",
      source: "src/components/arsip/RakGridModal.tsx",
      tokens: ['actionLabel="Lihat Dokumen"'],
    },
    kind: "picker",
    dataConditions: SUMMARY_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "storage-document-list-legacy",
    source: "src/components/arsip/DokumenModal.tsx",
    ordinal: 1,
    owner: "DokumenModal",
    routes: storageLegacyRoute,
    title: "Daftar Dokumen Rak",
    trigger: { label: "Lihat Dokumen", tokens: ["Preview dokumen", "onBack"] },
    kind: "picker",
    dataConditions: SUMMARY_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "storage-cabinet-grid",
    source: "src/components/arsip/LemariGridModal.tsx",
    ordinal: 1,
    owner: "LemariGridModal",
    routes: storageOverviewRoute,
    title: "Daftar Lemari",
    trigger: {
      label: "Lihat Lemari",
      source: "src/components/arsip-digital/pages/TempatPenyimpananPageClient.tsx",
      tokens: ['actionLabel="Lihat Lemari"', "setSelectedKantor"],
    },
    kind: "picker",
    dataConditions: SUMMARY_DATA,
    viewport: { desktop: "needs-fix", tablet: "not-verified", mobile: "passed" },
    evidence: "visual",
  },
  {
    id: "storage-rack-grid",
    source: "src/components/arsip/RakGridModal.tsx",
    ordinal: 1,
    owner: "RakGridModal",
    routes: storageOverviewRoute,
    title: "Daftar Rak",
    trigger: { label: "Lihat Rak", source: "src/components/arsip/LemariGridModal.tsx", tokens: ['actionLabel="Lihat Rak"'] },
    kind: "picker",
    dataConditions: SUMMARY_DATA,
    viewport: { desktop: "needs-fix", tablet: "not-verified", mobile: "passed" },
    evidence: "visual",
  },
  {
    id: "arsip-report-document-detail",
    source: "src/components/arsip-digital/laporan/ReportDocumentDetailModal.tsx",
    ordinal: 1,
    owner: "ReportDocumentDetailModal",
    routes: ["/dashboard/arsip-digital/laporan"],
    title: "Detail Dokumen",
    trigger: { label: "Detail", source: "src/app/dashboard/arsip-digital/laporan/page.tsx", tokens: ["ReportDocumentDetailModal"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "disposisi-pengajuan-form",
    source: "src/components/arsip-digital/pages/PengajuanDisposisiPageClient.tsx",
    ordinal: 1,
    owner: "PengajuanDisposisiPageClient",
    routes: ["/dashboard/arsip-digital/disposisi/pengajuan"],
    title: "Ajukan Disposisi",
    trigger: { label: "Ajukan Disposisi", tokens: ["Ajukan Disposisi", "setShowModal(true)"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "dashboard-npf-detail",
    source: "src/components/dashboard/KolektibilitasTable.tsx",
    ordinal: 1,
    owner: "KolektibilitasTable",
    routes: dashboardRoute,
    title: "Nasabah Berdasarkan Kolektibilitas",
    trigger: { label: "Card kolektibilitas", tokens: ["openModal(item.level)"] },
    kind: "summary",
    dataConditions: SUMMARY_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "dashboard-marketing-detail",
    source: "src/components/dashboard/LaporanAktivitasMarketingSection.tsx",
    ordinal: 1,
    owner: "LaporanAktivitasMarketingSection",
    routes: dashboardRoute,
    title: "Detail Aktivitas Marketing",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setActiveItem(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "dashboard-third-party-summary",
    source: "src/components/dashboard/LaporanPihakKetigaSection.tsx",
    ordinal: 1,
    owner: "LaporanPihakKetigaSection",
    routes: dashboardRoute,
    title: "Progress Pihak Ketiga",
    trigger: { label: "Lihat Detail", tokens: ["Lihat Detail", "openCategory(item.kategori)"] },
    kind: "summary",
    dataConditions: SUMMARY_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "visual",
  },
  {
    id: "dashboard-third-party-detail",
    source: "src/components/dashboard/LaporanPihakKetigaSection.tsx",
    ordinal: 2,
    owner: "LaporanPihakKetigaSection",
    routes: dashboardRoute,
    title: "Detail Progress Pihak Ketiga / Klaim",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailTarget(row)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "dashboard-deposit-summary",
    source: "src/components/dashboard/LaporanTitipanSection.tsx",
    ordinal: 1,
    owner: "LaporanTitipanSection",
    routes: dashboardRoute,
    title: "Laporan Dana Titipan",
    trigger: { label: "Lihat Detail", tokens: ["Lihat Detail", "openDepositSummary(item.jenisTitipan)"] },
    kind: "summary",
    dataConditions: SUMMARY_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "visual",
  },
  {
    id: "dashboard-deposit-detail",
    source: "src/components/dashboard/LaporanTitipanSection.tsx",
    ordinal: 2,
    owner: "LaporanTitipanSection",
    routes: dashboardRoute,
    title: "Detail Dana Titipan",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailTarget(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "collateral-expiry-monitoring",
    source: "src/components/informasi-debitur/CollateralMonitoring.tsx",
    ordinal: 1,
    owner: "CollateralExpiryModal",
    routes: ["/dashboard/informasi-debitur", "/dashboard/informasi-debitur/[id]"],
    title: "Atur Monitoring Expired",
    trigger: { label: "Atur Monitoring", source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx", tokens: ["onEditExpiry"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "debtor-master-detail",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 1,
    owner: "DebtorDetailModal",
    routes: ["/dashboard/informasi-debitur/master-debitur"],
    title: "Detail Debitur",
    trigger: { label: "Detail", tokens: ["<DebtorDetailModal", "openDetail"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-contract-detail",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 2,
    owner: "ContractDetailModal",
    routes: ["/dashboard/informasi-debitur", "/dashboard/informasi-debitur/master-debitur"],
    title: "Detail Kontrak",
    trigger: { label: "Detail kontrak", tokens: ["<ContractDetailModal", "setSelectedContract"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-collateral-detail",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 3,
    owner: "CollateralDetailModal",
    routes: ["/dashboard/informasi-debitur"],
    title: "Detail Agunan A01",
    trigger: { label: "Detail agunan", tokens: ["<CollateralDetailModal", "setSelectedCollateral"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-master-form",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 4,
    owner: "DebtorFormModal",
    routes: ["/dashboard/informasi-debitur/master-debitur"],
    title: "Tambah / Edit Debitur",
    trigger: { label: "Tambah Debitur atau Edit", tokens: ["openCreateDebtor", "openEditDebtor"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-contract-form",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 5,
    owner: "ContractFormModal",
    routes: ["/dashboard/informasi-debitur/master-debitur"],
    title: "Tambah / Edit Kontrak",
    trigger: { label: "Tambah Kontrak atau Edit", tokens: ["openAddContract", "openEditContract"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-expiry-import",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 6,
    owner: "DebtorListClient",
    routes: ["/dashboard/informasi-debitur"],
    title: "Upload Excel Expired Agunan",
    trigger: { label: "Upload Excel Expired", tokens: ["Upload Excel Expired", "openExpiryImport"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-marketing-form",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 7,
    owner: "MarketingFormModal",
    routes: debtorMarketingRoutes,
    title: "Tambah / Edit Aktivitas Marketing",
    trigger: { label: "Tambah atau Edit aktivitas", tokens: ["openCreate", "openEdit(item)"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-marketing-detail",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 8,
    owner: "MarketingDetailModal",
    routes: debtorMarketingRoutes,
    title: "Detail Aktivitas Marketing",
    trigger: { label: "Detail", tokens: ["<MarketingDetailModal", "setDetail(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-import-job-detail",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 9,
    owner: "ImportJobDetailModal",
    routes: debtorImportRoutes,
    title: "Detail Job Import",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedImportJob(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-ideb-resolve",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 10,
    owner: "IdebResolveModal",
    routes: [
      "/dashboard/informasi-debitur/admin/monitoring-import",
      "/dashboard/informasi-debitur/admin/upload-ideb",
    ],
    title: "Detail IDEB Belum Terhubung",
    trigger: { label: "Hubungkan IDEB", tokens: ['label: "Hubungkan IDEB"', "setSelectedPendingIdeb(item)"] },
    kind: "workflow",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-import-form",
    source: "src/components/informasi-debitur/DebiturModuleClients.tsx",
    ordinal: 11,
    owner: "DebtorImportClient",
    routes: debtorImportRoutes,
    title: "Upload SLIK / IDEB",
    trigger: { label: "Upload File", tokens: ['label="Upload File"', "openUpload"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "ideb-report-detail",
    source: "src/components/informasi-debitur/DebtorIdebReportClient.tsx",
    ordinal: 1,
    owner: "DebtorIdebReportClient",
    routes: ["/dashboard/informasi-debitur/laporan-ideb"],
    title: "Detail Pengecekan IDEB",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "openDetail(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "debtor-detail-document-upload",
    source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx",
    ordinal: 1,
    owner: "DebtorDocumentUploadModal",
    routes: debtorDetailRoute,
    title: "Upload Dokumen Wajib / Dokumen Lainnya",
    trigger: { label: "Upload Dokumen", tokens: ["openChecklistDocumentUpload", "openOtherDocumentUpload"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-detail-warning-upload",
    source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx",
    ordinal: 2,
    owner: "DebtorWarningLetterUploadModal",
    routes: debtorDetailRoute,
    title: "Upload Surat Peringatan",
    trigger: { label: "Upload Surat Peringatan", tokens: ["Upload Surat Peringatan", "openWarningLetterUpload"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-detail-marketing-activity",
    source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx",
    ordinal: 3,
    owner: "SummaryTab",
    routes: debtorDetailRoute,
    title: "Detail Aktivitas Marketing",
    trigger: {
      label: "Buka detail aktivitas",
      tokens: ["setSelectedEntry(entry)", "Buka detail ${meta.label}"],
    },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "debtor-detail-ideb",
    source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx",
    ordinal: 4,
    owner: "IdebTab",
    routes: debtorDetailRoute,
    title: "Detail Pengecekan IDEB",
    trigger: {
      label: "Buka detail IDEB",
      tokens: ["openIdebDetail", "Detail Pengecekan IDEB"],
    },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "debtor-detail-collateral",
    source: "src/components/informasi-debitur/DebtorWorkflowDetailClient.tsx",
    ordinal: 5,
    owner: "AgunanDetailModal",
    routes: debtorDetailRoute,
    title: "Detail Agunan",
    trigger: { label: "Detail", tokens: ["setSelectedCollateral(item)", 'label: "Detail"'] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: MOBILE_NEEDS_FIX,
    evidence: "visual",
  },
  {
    id: "legal-progress-form",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 1,
    owner: "LegalProgressClient",
    routes: legalProgressRoutes,
    title: "Tambah / Ubah Progress Pihak Ketiga",
    trigger: { label: "Tambah Progress atau Ubah", tokens: ["Tambah Progress", 'label: "Ubah"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-progress-detail",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 2,
    owner: "LegalProgressClient",
    routes: legalProgressRoutes,
    title: "Detail Progress Pihak Ketiga",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailTarget(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-claim-form",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 3,
    owner: "LegalClaimClient",
    routes: ["/dashboard/legal/progress/klaim"],
    title: "Tambah / Ubah Klaim Asuransi",
    trigger: { label: "Tambah Klaim atau Ubah", tokens: ["Tambah Klaim", 'label: "Ubah"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-claim-detail",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 4,
    owner: "LegalClaimClient",
    routes: ["/dashboard/legal/progress/klaim"],
    title: "Detail Klaim Asuransi",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailTarget(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-deposit-form",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 5,
    owner: "LegalDepositClient",
    routes: legalDepositRoutes,
    title: "Tambah / Ubah Dana Titipan",
    trigger: { label: "Tambah Titipan atau Ubah", tokens: ["Tambah Titipan", 'label: "Ubah"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-deposit-transaction-form",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 6,
    owner: "LegalDepositClient",
    routes: legalDepositRoutes,
    title: "Tambah Transaksi Titipan",
    trigger: {
      label: "Transaksi",
      tokens: ['label: "Transaksi"', "setTransactionTarget(item)"],
    },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-deposit-detail",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 7,
    owner: "LegalDepositClient",
    routes: legalDepositRoutes,
    title: "Detail Dana Titipan",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setHistoryTarget(item)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "legal-activity-audit-detail",
    source: "src/components/legal/LegalModuleClients.tsx",
    ordinal: 8,
    owner: "LegalActivityLogSection",
    routes: ["/dashboard/legal/laporan"],
    title: "Detail Audit Aktivitas Legal",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setDetailTarget(item)"] },
    kind: "audit",
    dataConditions: DETAIL_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "visual",
  },
  {
    id: "persuratan-print-detail",
    source: "src/components/manajemen-surat/CetakDokumenClient.tsx",
    ordinal: 1,
    owner: "PrintDocumentDetailModal",
    routes: ["/dashboard/manajemen-surat/cetak-dokumen"],
    title: "Detail Dokumen Cetak",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "handleOpenDetail(record)"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "persuratan-edit-form",
    source: "src/components/manajemen-surat/LaporanPersuratanClient.tsx",
    ordinal: 1,
    owner: "EditCorrespondenceModal",
    routes: ["/dashboard/manajemen-surat/laporan"],
    title: "Edit Surat Masuk / Surat Keluar / Memorandum",
    trigger: { label: "Edit", tokens: ['label: "Edit"', "EditCorrespondenceModal"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "visual",
  },
  {
    id: "persuratan-report-detail",
    source: "src/components/manajemen-surat/LaporanPersuratanClient.tsx",
    ordinal: 2,
    owner: "LaporanPersuratanClient",
    routes: ["/dashboard/manajemen-surat/laporan"],
    title: "Detail Surat Masuk / Surat Keluar / Memorandum",
    trigger: { label: "Detail", tokens: ['label: "Detail"', "setSelectedDetail"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "memorandum-disposition-form",
    source: "src/components/manajemen-surat/MemorandumDisposisiModal.tsx",
    ordinal: 1,
    owner: "MemorandumDisposisiModal",
    routes: ["/dashboard/manajemen-surat/laporan"],
    title: "Disposisi / Redisposisi Memorandum",
    trigger: { label: "Disposisi atau Redisposisi", source: "src/components/manajemen-surat/LaporanPersuratanClient.tsx", tokens: ["MemorandumDisposisiModal"] },
    kind: "workflow",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "surat-masuk-disposition-form",
    source: "src/components/manajemen-surat/SuratMasukDisposisiModal.tsx",
    ordinal: 1,
    owner: "SuratMasukDisposisiModal",
    routes: ["/dashboard/manajemen-surat/laporan"],
    title: "Disposisi / Redisposisi Surat Masuk",
    trigger: { label: "Disposisi atau Redisposisi", source: "src/components/manajemen-surat/LaporanPersuratanClient.tsx", tokens: ["SuratMasukDisposisiModal"] },
    kind: "workflow",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "parameter-master-form",
    source: "src/components/parameter/ParameterMasterPage.tsx",
    ordinal: 1,
    owner: "ParameterMasterPage",
    routes: parameterMasterRoutes,
    title: "Tambah / Edit Parameter Master",
    trigger: { label: "Tambah atau Edit parameter", tokens: ["config.addLabel", 'label: "Edit"'] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "persuratan-deadline-form",
    source: "src/components/surat/TenggatWaktuModal.tsx",
    ordinal: 1,
    owner: "TenggatWaktuModal",
    routes: [
      "/dashboard/manajemen-surat/kelola-surat/input-memorandum",
      "/dashboard/manajemen-surat/kelola-surat/input-surat-masuk",
    ],
    title: "Atur Tenggat Waktu",
    trigger: { label: "Simpan surat atau memorandum", tokens: ["handleSave", "handleSkip"] },
    kind: "workflow",
    dataConditions: FORM_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "shared-delete-confirmation",
    source: "src/components/ui/DeleteConfirmModal.tsx",
    ordinal: 1,
    owner: "DeleteConfirmModal",
    routes: ["shared"],
    title: "Konfirmasi Hapus",
    trigger: {
      label: "Hapus",
      tokens: ["onConfirm", "uiverse-modal-button--danger"],
    },
    kind: "confirmation",
    dataConditions: DETAIL_DATA,
    viewport: PASS_ALL,
    evidence: "visual",
  },
  {
    id: "seputar-jaminan-catalog-form",
    source: "src/components/seputar-jaminan/SeputarJaminanCatalogClient.tsx",
    ordinal: 1,
    owner: "SeputarJaminanCatalogClient",
    routes: ["/dashboard/seputar-jaminan/katalog"],
    title: "Buat atau Perbarui Draf Katalog",
    trigger: { label: "Buat katalog", tokens: ["setFormOpen(true)", "Buat katalog"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "source-only",
  },
  {
    id: "seputar-jaminan-catalog-detail",
    source: "src/components/seputar-jaminan/SeputarJaminanCatalogClient.tsx",
    ordinal: 2,
    owner: "SeputarJaminanCatalogClient",
    routes: ["/dashboard/seputar-jaminan/katalog"],
    title: "Detail Katalog",
    trigger: { label: "Lihat detail", tokens: ["openDetail", "Lihat detail"] },
    kind: "detail",
    dataConditions: DETAIL_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "source-only",
  },
  {
    id: "seputar-jaminan-review-decision",
    source: "src/components/seputar-jaminan/SeputarJaminanReviewClient.tsx",
    ordinal: 1,
    owner: "SeputarJaminanReviewClient",
    routes: ["/dashboard/seputar-jaminan/pemeriksaan"],
    title: "Keputusan Pemeriksaan",
    trigger: { label: "Setujui atau minta perbaikan", tokens: ["begin(", "Setujui & tayangkan"] },
    kind: "confirmation",
    dataConditions: DETAIL_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "source-only",
  },
  {
    id: "seputar-jaminan-contact-form",
    source: "src/components/seputar-jaminan/SeputarJaminanProfileContactClient.tsx",
    ordinal: 1,
    owner: "SeputarJaminanProfileContactClient",
    routes: ["/dashboard/seputar-jaminan/profil-kontak"],
    title: "Tambah atau Perbarui Kontak WhatsApp",
    trigger: { label: "Tambah kontak", tokens: ["setContactModalOpen(true)", "Tambah kontak"] },
    kind: "form",
    dataConditions: FORM_DATA,
    viewport: NEEDS_FIX_ALL,
    evidence: "source-only",
  },
];

const ALL_VIEWPORTS = ["desktop", "tablet", "mobile"] as const;

function allViewportEvidence(spec: string): ModalRuntimeEvidence {
  return {
    desktop: [spec],
    tablet: [spec],
    mobile: [spec],
  };
}

const REMEDIATION_SPEC = "tests/e2e/modal-remediation.dashboard.spec.ts";
const DASHBOARD_SPEC = "tests/e2e/dashboard.spec.ts";
const LEGAL_DASHBOARD_SPEC =
  "tests/e2e/legal-report-details.dashboard.spec.ts";
const STORAGE_SPEC = "tests/e2e/storage-modals.dashboard.spec.ts";
const WORKFLOW_SPEC = "tests/e2e/modal-workflows.dashboard.spec.ts";
const CALLER_MATRIX_DASHBOARD_SPEC =
  "tests/e2e/modal-caller-matrix.dashboard.spec.ts";
const FINAL_REMAINING_SPEC =
  "tests/e2e/modal-final-remaining.dashboard.spec.ts";
const DEBTOR_REMAINING_SPEC =
  "tests/e2e/modal-debtor-remaining.dashboard.spec.ts";
const PERSURATAN_NOTIFICATION_SPEC =
  "tests/e2e/persuratan-notification.dashboard.spec.ts";
const SEPUTAR_JAMINAN_MODALS_SPEC =
  "tests/e2e/seputar-jaminan-modals.dashboard.spec.ts";

/**
 * Bukti di bawah hanya berisi modal yang benar-benar dibuka oleh browser E2E.
 * Keberadaan caller di source tidak otomatis dimasukkan sebagai bukti runtime.
 */
export const MODAL_RUNTIME_EVIDENCE: Readonly<
  Record<string, ModalRuntimeEvidence>
> = {
  "seputar-jaminan-catalog-form": allViewportEvidence(
    SEPUTAR_JAMINAN_MODALS_SPEC,
  ),
  "seputar-jaminan-catalog-detail": allViewportEvidence(
    SEPUTAR_JAMINAN_MODALS_SPEC,
  ),
  "seputar-jaminan-review-decision": allViewportEvidence(
    SEPUTAR_JAMINAN_MODALS_SPEC,
  ),
  "seputar-jaminan-contact-form": allViewportEvidence(
    SEPUTAR_JAMINAN_MODALS_SPEC,
  ),
  "activity-centre-detail": allViewportEvidence(REMEDIATION_SPEC),
  "collateral-expiry-monitoring": allViewportEvidence(REMEDIATION_SPEC),
  "dashboard-deposit-detail": allViewportEvidence(LEGAL_DASHBOARD_SPEC),
  "dashboard-deposit-summary": allViewportEvidence(LEGAL_DASHBOARD_SPEC),
  "dashboard-marketing-detail": allViewportEvidence(DASHBOARD_SPEC),
  "dashboard-third-party-detail": allViewportEvidence(LEGAL_DASHBOARD_SPEC),
  "dashboard-third-party-summary": allViewportEvidence(LEGAL_DASHBOARD_SPEC),
  "dashboard-npf-detail": allViewportEvidence(FINAL_REMAINING_SPEC),
  "debtor-detail-collateral": allViewportEvidence(REMEDIATION_SPEC),
  "debtor-detail-ideb": allViewportEvidence(REMEDIATION_SPEC),
  "debtor-master-detail": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-contract-detail": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-collateral-detail": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-master-form": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-contract-form": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-expiry-import": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-marketing-form": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-marketing-detail": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-import-job-detail": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-ideb-resolve": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-import-form": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "debtor-detail-document-upload": allViewportEvidence(
    DEBTOR_REMAINING_SPEC,
  ),
  "debtor-detail-warning-upload": allViewportEvidence(
    DEBTOR_REMAINING_SPEC,
  ),
  "debtor-detail-marketing-activity": allViewportEvidence(
    DEBTOR_REMAINING_SPEC,
  ),
  "disposisi-historis-detail": allViewportEvidence(WORKFLOW_SPEC),
  "disposisi-permintaan-action": allViewportEvidence(WORKFLOW_SPEC),
  "disposisi-pengajuan-form": allViewportEvidence(REMEDIATION_SPEC),
  "dokumen-list-detail": allViewportEvidence(WORKFLOW_SPEC),
  "dokumen-list-edit": allViewportEvidence(WORKFLOW_SPEC),
  "ideb-report-detail": allViewportEvidence(REMEDIATION_SPEC),
  "legal-activity-audit-detail": allViewportEvidence(REMEDIATION_SPEC),
  "peminjaman-approval-action": allViewportEvidence(WORKFLOW_SPEC),
  "peminjaman-approval-detail": allViewportEvidence(WORKFLOW_SPEC),
  "peminjaman-historis-detail": allViewportEvidence(WORKFLOW_SPEC),
  "peminjaman-laporan-detail": allViewportEvidence(REMEDIATION_SPEC),
  "peminjaman-request-form": allViewportEvidence(REMEDIATION_SPEC),
  "penyimpanan-historis-detail": allViewportEvidence(WORKFLOW_SPEC),
  "persuratan-edit-form": allViewportEvidence(REMEDIATION_SPEC),
  "persuratan-deadline-form": allViewportEvidence(FINAL_REMAINING_SPEC),
  "storage-document-list": allViewportEvidence(STORAGE_SPEC),
  "storage-document-list-legacy": allViewportEvidence(FINAL_REMAINING_SPEC),
  "storage-cabinet-grid": allViewportEvidence(STORAGE_SPEC),
  "storage-rack-grid": allViewportEvidence(STORAGE_SPEC),
  "arsip-report-document-detail": allViewportEvidence(WORKFLOW_SPEC),
  "memorandum-disposition-form": allViewportEvidence(WORKFLOW_SPEC),
  "surat-masuk-disposition-form": allViewportEvidence(WORKFLOW_SPEC),
  "parameter-divisi-form": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "parameter-jenis-dokumen-form": allViewportEvidence(
    CALLER_MATRIX_DASHBOARD_SPEC,
  ),
  "parameter-prioritas-surat-form": allViewportEvidence(
    CALLER_MATRIX_DASHBOARD_SPEC,
  ),
  "parameter-role-form": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "parameter-role-menu-feature": allViewportEvidence(
    CALLER_MATRIX_DASHBOARD_SPEC,
  ),
  "parameter-tempat-penyimpanan-form": allViewportEvidence(
    CALLER_MATRIX_DASHBOARD_SPEC,
  ),
  "parameter-master-form": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "users-form": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "users-invitation-ready": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "users-access-action": allViewportEvidence(CALLER_MATRIX_DASHBOARD_SPEC),
  "users-delete-confirmation": allViewportEvidence(
    CALLER_MATRIX_DASHBOARD_SPEC,
  ),
  "shared-delete-confirmation": allViewportEvidence(DEBTOR_REMAINING_SPEC),
  "legal-progress-form": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-progress-detail": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-claim-form": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-claim-detail": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-deposit-form": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-deposit-detail": allViewportEvidence(FINAL_REMAINING_SPEC),
  "legal-deposit-transaction-form": allViewportEvidence(
    FINAL_REMAINING_SPEC,
  ),
  "persuratan-print-detail": allViewportEvidence(
    PERSURATAN_NOTIFICATION_SPEC,
  ),
  "persuratan-report-detail": allViewportEvidence(
    PERSURATAN_NOTIFICATION_SPEC,
  ),
};

export const MODAL_CALLER_BASELINE: readonly ModalCallerBaseline[] =
  MODAL_CALLER_SOURCE_INVENTORY.map((caller) => {
    const runtimeEvidence = MODAL_RUNTIME_EVIDENCE[caller.id] ?? {};
    const viewport = Object.fromEntries(
      ALL_VIEWPORTS.map((name) => [
        name,
        runtimeEvidence[name]?.length ? "passed" : "not-verified",
      ]),
    ) as ModalCallerBaseline["viewport"];

    return {
      ...caller,
      viewport,
      evidence: Object.values(runtimeEvidence).some(
        (references) => references && references.length > 0,
      )
        ? "runtime-e2e"
        : "source-only",
      runtimeEvidence,
    };
  });

export function summarizeModalRuntimeEvidence() {
  return Object.fromEntries(
    ALL_VIEWPORTS.map((viewport) => {
      const passed = MODAL_CALLER_BASELINE.filter(
        (caller) => caller.viewport[viewport] === "passed",
      ).length;
      return [
        viewport,
        {
          passed,
          notVerified: MODAL_CALLER_BASELINE.length - passed,
          total: MODAL_CALLER_BASELINE.length,
        },
      ];
    }),
  ) as Record<
    (typeof ALL_VIEWPORTS)[number],
    { passed: number; notVerified: number; total: number }
  >;
}
